import type { Lexicon } from "./concepts";

export const en: Lexicon = {
  lang: "en",
  needsReview: false,
  patterns: {
    GUARANTEE: [
      "guaranteed",
      "guarantee",
      "guaranteed returns",
      "guaranteed profit",
      "assured return",
      "assured returns",
      "assured profit",
      "fixed return",
      "fixed returns",
      "fixed monthly income",
      "sure shot",
      "sureshot",
      "100% sure",
      "100 percent sure",
      "100% profit",
      "100% safe",
      "risk free",
      "risk-free",
      "zero risk",
      "no risk",
      "without any risk",
      "confirmed profit",
      "promised returns",
      "profit guaranteed",
      "money back guarantee",
    ],
    URGENCY: [
      "limited seats",
      "seats left",
      "seats are left",
      "only few seats",
      "last chance",
      "last day",
      "today only",
      "offer ends",
      "offer closes",
      "hurry",
      "hurry up",
      "join now",
      "act now",
      "register now",
      "before it is too late",
      "closing soon",
      "few hours left",
      "don't miss",
      "dont miss",
      "missing out",
      /* Pressure that is not selling anything. Everything above this line is
         sales language from an investment pitch — "seats left", "join now" —
         which left the concept blind to the way a phishing message hurries
         somebody: a deadline, a threat to an account, and an instruction to
         pay or click at once. A real message from a bank or a courier does
         not usually talk like this either. */
      "immediately",
      "urgently",
      "right now",
      "right away",
      "at once",
      "without delay",
      "within 24 hours",
      "within 2 hours",
      "within one hour",
      "within an hour",
      "expire today",
      "expires today",
      "will expire",
      "about to expire",
      "will be blocked",
      "will be suspended",
      "will be deactivated",
      "account will be closed",
      "final notice",
      "last warning",
      "immediate action",
      "act fast",
      "pay now",
      "transfer now",
      "send now",
      "click now",
      "update now",
      "verify now",
    ],
    VIP_GROUP: [
      "vip group",
      "vip premium",
      "premium group",
      "institutional group",
      "private group",
      "paid group",
      "free trading course",
      "free course",
      "stock club",
      "investment club",
      "exclusive group",
      "members only group",
      "add you to the group",
      "join the group",
      "join our group",
      "telegram channel",
      "whatsapp group",
    ],
    INSIDER: [
      "insider",
      "insider information",
      "insider info",
      "inside information",
      "operator call",
      "operator calls",
      "operator",
      "bulk deal info",
      "block deal info",
      "pre-ipo",
      "pre ipo",
      "guaranteed ipo allotment",
      "sure allotment",
      "confirmed allotment",
      "institutional account",
      "discounted ipo",
      "jackpot call",
      "jackpot calls",
      "unpublished information",
    ],
    DOUBLE_MONEY: [
      "double your money",
      "money doubled",
      "double the money",
      "doubling your capital",
      "2x your money",
      "3x your money",
      "triple your money",
      "money will double",
    ],
    OTP: [
      "otp",
      "one time password",
      "share the otp",
      "send the otp",
      "tell me the otp",
      "pin",
      "atm pin",
      "upi pin",
      "cvv",
      "password",
      "verification code",
      "share code",
      "share the code",
      "read out the code",
    ],
    FEE_TO_WITHDRAW: [
      "tax to withdraw",
      "pay tax to withdraw",
      "tax first to withdraw",
      "pay tax first",
      "fee to withdraw",
      "pay to withdraw",
      "release funds",
      "release the funds",
      "release charges",
      "withdrawal fee",
      "withdrawal charges",
      "processing fee",
      "security deposit",
      "kyc fee",
      "kyc charges",
      "clearance charge",
      "clearance fee",
      "recovery charge",
      "recovery charges",
      "recovery fee",
      "gst to release",
      "unlock account",
      "unlock your account",
      "account is on hold",
      "withdrawal is on hold",
      "recovery agent",
      "recovery fee",
      "convert to withdraw",
    ],
    REMOTE_ACCESS: [
      "anydesk",
      "teamviewer",
      "quicksupport",
      "rustdesk",
      "screen share",
      "share your screen",
      "share screen",
      "install this app from link",
      "install from this link",
      "download the apk",
      "apk",
      "sideload",
      "allow remote access",
    ],
    SECRECY: [
      "don't tell anyone",
      "dont tell anyone",
      "do not tell anyone",
      "keep it secret",
      "keep this secret",
      "keep this confidential",
      "confidential",
      "only for you",
      "between us",
      "not even family",
    ],
    SEBI_APPROVED: [
      "sebi approved",
      "sebi certified",
      "sebi verified",
      "sebi verified group",
      "approved by sebi",
      "government approved",
      "rbi approved",
      "exchange approved",
    ],
    FAKE_PROOF: [
      "profit screenshot",
      "profit screenshots",
      "our members profit",
      "members' profit",
      "yesterday's profit",
      "yesterday profit",
      "today's profit",
      "see the profit",
      "testimonial",
      "testimonials",
      "payout proof",
      "withdrawal proof",
    ],
    SMALL_CAPITAL: [
      "small capital big profit",
      "small capital",
      "10k to 1 lakh",
      "turn 10000 into",
      "intraday jackpot",
      "expiry hero zero",
      "hero zero",
      "little money big returns",
    ],
    BORROWED: [
      "instant loan to invest",
      "loan to invest",
      "loan to trade",
      "gold loan to invest",
      "credit card to invest",
      "borrow and invest",
      "take a loan and",
    ],
    CRYPTO_BOT: [
      "crypto arbitrage",
      "arbitrage bot",
      "trading bot",
      "ai trading bot",
      "binary options",
      "forex signals",
      "forex trading signals",
      "mining plan",
      "usdt doubling",
    ],
    AUTHORITY_NAME: [
      "as seen on",
      "featured on",
      "backed by",
      "recommended by",
      "as shown on tv",
    ],
  },
};
