import type { Lexicon } from "./concepts";

/* Hindi written in Latin letters, as people type it on WhatsApp. Spelling
   varies a lot, so the common variants are listed rather than guessed. */
export const hinglish: Lexicon = {
  lang: "hinglish",
  needsReview: false,
  patterns: {
    GUARANTEE: [
      "pakka profit",
      "pakka munafa",
      "pakka munaafa",
      "pakka paisa",
      "pakki guarantee",
      "100% pakka",
      "guarantee hai",
      "guarantee ke saath",
      "koi risk nahi",
      "koi risk nahin",
      "bina risk",
      "bina kisi risk",
      "risk free",
      "fix return",
      "fixed return",
      "nischit munafa",
      "nuksan nahi hoga",
      "nuksan nahin hoga",
      "koi loss nahi",
      "koi loss nahin",
      "loss ka sawal hi nahi",
      "loss hota hi nahi",
      "paisa doob nahi sakta",
    ],
    URGENCY: [
      "jaldi karo",
      "jaldi kijiye",
      "jaldi",
      "aaj hi",
      "aaj hi join",
      "abhi join",
      "abhi judiye",
      "turant",
      "turant kare",
      "seats bachi",
      "seat bachi",
      "sirf kuch seats",
      "aakhri mauka",
      "akhri mauka",
      "offer khatam",
      "der mat kijiye",
    ],
    VIP_GROUP: [
      "vip group",
      "premium group",
      "vip premium group",
      "group me judiye",
      "group me jude",
      "group me add",
      "group join kare",
      "channel join kare",
      "free course",
      "muft course",
      "paid group",
    ],
    INSIDER: [
      "andar ki khabar",
      "andar ki baat",
      "insider info",
      "insider khabar",
      "operator",
      "operator ki call",
      "ipo allotment pakka",
      "allotment pakka",
      "jackpot",
      "jackpot call",
      "upar se khabar",
    ],
    DOUBLE_MONEY: [
      "paisa double",
      "paise double",
      "paisa doguna",
      "doguna",
      "dugna",
      "double ho jayega",
      "double kar denge",
      "teen guna",
    ],
    OTP: [
      "otp batao",
      "otp bataiye",
      "otp bhejo",
      "otp bhejiye",
      "otp share",
      "otp do",
      "pin batao",
      "password batao",
      "code batao",
      "code bhejo",
    ],
    FEE_TO_WITHDRAW: [
      "tax bharo",
      "tax bhariye",
      "tax pehle bhariye",
      "tax pehle bharo",
      "tax jama karo",
      "paisa nikalne ke liye",
      "nikalne ke liye fees",
      "paisa release",
      "release charges",
      "release karne ke liye",
      "processing fee",
      "processing charges",
      "security deposit",
      "kyc fees",
      "account unlock",
      "account hold",
      "recovery agent",
      "paisa wapas dilayenge",
    ],
    REMOTE_ACCESS: [
      "anydesk",
      "anydesk download",
      "teamviewer",
      "screen share karo",
      "screen share kijiye",
      "screen dikhao",
      "apk download",
      "app install karo",
      "link se app install",
    ],
    SECRECY: [
      "kisi ko mat batana",
      "kisi ko mat bataiye",
      "kisi ko na batana",
      "secret rakhna",
      "secret rakhiye",
      "gupt rakhna",
      "sirf aapke liye",
      "ghar me mat batana",
    ],
    SEBI_APPROVED: [
      "sebi approved",
      "sebi certified",
      "sebi se approved",
      "sebi registered group",
      "sarkar se approved",
    ],
    FAKE_PROOF: [
      "aaj ka profit dekho",
      "aaj ka profit",
      "kal ka profit",
      "members ka profit",
      "profit screenshot",
      "screenshot dekhiye",
      "payout proof",
    ],
    SMALL_CAPITAL: [
      "kam paise me zyada profit",
      "kam paise me",
      "chhoti poonji badi kamai",
      "choti punji",
      "10 hazar se lakh",
      "intraday jackpot",
    ],
    BORROWED: [
      "loan lekar invest",
      "loan leke invest",
      "loan lekar trade",
      "udhar lekar",
      "gold loan lekar",
      "credit card se invest",
    ],
    CRYPTO_BOT: [
      "trading bot",
      "crypto double",
      "crypto arbitrage",
      "binary option",
      "forex signal",
      "usdt double",
      "mining plan",
    ],
    AUTHORITY_NAME: ["tv me aaya", "news me aaya", "bade log lagate hain"],
  },
};
